import test from 'node:test';import assert from 'node:assert/strict';import {demo} from '../public/demo.js';import {clone,validate,removeEntity} from '../public/model.js';
test('default topology has valid rack occupancy and network references',()=>validate(demo));
test('rejects duplicate IP and overlapping rack units',()=>{const p=clone(demo);p.devices[1].ip=p.devices[0].ip;assert.throws(()=>validate(p),/repetido/);const q=clone(demo);q.devices.find(d=>d.id==='fw').u=30;assert.throws(()=>validate(q),/ocupadas/);});
test('rejects devices exceeding rack capacity',()=>{const p=clone(demo);p.devices.find(d=>d.id==='host').u=42;assert.throws(()=>validate(p),/capacidade/);});
test('deleting a host cascades to VMs and cables without dangling references',()=>{const p=clone(demo);removeEntity(p,'devices','host');validate(p);assert(!p.devices.some(d=>d.type==='VM'));});
test('deleting a building cascades; deleting a rack preserves its equipment',()=>{const p=clone(demo);removeEntity(p,'sites','a');validate(p);assert(!p.devices.some(d=>d.site==='a'));const q=clone(demo);removeEntity(q,'racks','rack-dc');validate(q);assert.equal(q.devices.length,demo.devices.length);});

test('rack lock persists through serialization and prevents movement',async()=>{const {moveRack,worldPosition}=await import('../public/model.js');const p=clone(demo);const r=p.racks[0];r.locked=true;validate(p);const saved=clone(p);assert.equal(saved.racks[0].locked,true);assert.throws(()=>moveRack(saved,r.id,1,1),/bloqueada/);assert.equal(saved.racks[0].x,r.x);saved.racks[0].locked=false;const device=saved.devices.find(d=>d.rack===r.id);const before=worldPosition(saved,device);moveRack(saved,r.id,1,1);assert.equal(worldPosition(saved,device).x,before.x+1);assert.equal(worldPosition(saved,device).z,before.z+1);validate(saved);});
test('rack dragging clamps to building bounds and supports existing projects without lock fields',async()=>{const {moveRack}=await import('../public/model.js');const p=clone(demo);moveRack(p,'rack-a',999,-999);validate(p);assert.equal(p.racks.find(r=>r.id==='rack-a').x,2.3);assert.equal(p.racks.find(r=>r.id==='rack-a').z,-1.55);});
