import test from 'node:test';import assert from 'node:assert/strict';
import {makeExample} from '../public/examples.js';
import {normalizeProject,validate,clone} from '../public/model.js';
import {createRoomDevices,duplicateRoom,duplicateDevice,updateDevices,roomTasks,changeDescription} from '../public/room-actions.js';
import {makeBlockPlan} from '../public/plan-blocks.js';
const fixture=()=>{const p=makeExample('connections');normalizeProject(p);return p;};
test('quick creation inherits room, floor and site, with unique names and no invented links',()=>{const p=fixture(),room=p.rooms[0],before=clone(p),ids=createRoomDevices(p,{roomId:room.id,name:'Posto',type:'Posto de trabalho',quantity:6});normalizeProject(p);validate(p);assert.equal(ids.length,6);for(const id of ids){const d=p.devices.find(d=>d.id===id);assert.equal(d.room,room.id);assert.equal(d.floor,room.floor);assert.equal(d.ip,'');assert.equal(d.vlan,0);}assert.equal(new Set(p.devices.map(d=>d.name)).size,p.devices.length);assert.equal(p.links.length,before.links.length);assert.equal(changeDescription(before,p),'adicionar 6 equipamentos');assert.throws(()=>createRoomDevices(p,{roomId:room.id,name:'PC',type:'Computador',quantity:0}),/1 e 20/);});
test('duplicating a furnished room preserves originals and stores separate proposals',()=>{const p=fixture(),room=p.rooms.find(r=>p.devices.some(d=>d.room===r.id&&p.links.some(l=>l.a===d.id))),before=clone(p);const original=p.devices.find(d=>d.room===room.id);original.record={owner:'Pessoa',serial:'123'};original.attachments=[];const id=duplicateRoom(p,room.id,'Nova sala');normalizeProject(p);validate(p);assert.deepEqual(p.links,before.links);const copied=p.devices.filter(d=>d.room===id);assert.equal(copied.length,before.devices.filter(d=>d.room===room.id).length);assert.ok(copied.every(d=>!d.ip&&!d.record&&!d.attachments));for(const l of p.connectionProposals){assert.ok(copied.some(d=>d.id===l.a));assert.ok(copied.some(d=>d.id===l.b));assert.ok(!p.links.some(x=>x.id===l.id));}assert.equal(original.record.owner,'Pessoa');});
test('bulk updates enforce rack/VM location ownership and preserve identity',()=>{const p=fixture(),room=p.rooms[0],ids=createRoomDevices(p,{roomId:room.id,name:'Novo',type:'Computador',quantity:2});updateDevices(p,ids,{owner:'Ana'});assert.ok(ids.every(id=>p.devices.find(d=>d.id===id).record.owner==='Ana'));const target=p.rooms.at(-1);updateDevices(p,ids,{roomId:target.id});normalizeProject(p);validate(p);assert.ok(ids.every(id=>p.devices.find(d=>d.id===id).room===target.id));const mounted=p.devices.find(d=>d.rack);assert.throws(()=>updateDevices(p,[mounted.id],{roomId:target.id}),/bastidores/);});
test('device copy removes unique records and does not duplicate live cables',()=>{const p=fixture(),d=p.devices.find(d=>d.type==='Computador'||d.type==='Posto de trabalho');d.record={serial:'unique',owner:'Pessoa'};const n=p.links.length,id=duplicateDevice(p,d.id),copy=p.devices.find(x=>x.id===id);normalizeProject(p);validate(p);assert.equal(copy.ip,'');assert.equal(copy.record,undefined);assert.equal(p.links.length,n);assert.equal(copy.room,d.room);});
test('room tasks and map drill-down expose actionable objects',()=>{const p=fixture(),room=p.rooms[0],id=createRoomDevices(p,{roomId:room.id,name:'Por ligar',type:'Computador'})[0];assert.ok(roomTasks(p,room.id).some(t=>t.device===id));const summary=makeBlockPlan({project:p,floorId:room.floor,overviewRooms:true});assert.match(summary,/data-plan-type="rooms"/);assert.ok(!summary.includes('data-plan-id="'+id+'"'));const inside=makeBlockPlan({project:p,floorId:room.floor,roomId:room.id,overviewRooms:true});assert.ok(inside.includes('data-plan-id="'+id+'"'));});
test('proposal validation rejects invalid endpoints and duplicate ids',()=>{const p=fixture();p.connectionProposals=[{id:'proposed',a:p.devices[0].id,b:'absent',portA:'P1',portB:'F1',kind:'copper'}];assert.throws(()=>validate(p),/Proposta/);});

test('moving a physical server across buildings moves its hosted VMs coherently',()=>{const p=fixture(),room=p.rooms[0],hostId=createRoomDevices(p,{roomId:room.id,name:'Host novo',type:'Servidor'})[0],host=p.devices.find(d=>d.id===hostId);p.devices.push({...clone(host),id:'vm-move-test',name:'VM de teste',type:'VM',host:hostId,portCount:1});const site={...clone(p.sites[0]),id:'destination-site',name:'Outro edifício',x:80,z:80};p.sites.push(site);p.floors.push({id:'destination-floor',name:'Piso 0',site:site.id,level:0,elevation:0});p.rooms.push({id:'destination-room',name:'Sala',floor:'destination-floor',x:0,z:0,w:4,d:3});updateDevices(p,[hostId],{roomId:'destination-room'});normalizeProject(p);validate(p);const vm=p.devices.find(d=>d.id==='vm-move-test');assert.equal(vm.site,site.id);assert.equal(vm.room,'destination-room');assert.equal(vm.host,hostId);});
test('mini-switch with occupied uplink still reports a missing upstream continuation',()=>{const p=fixture(),mini=p.devices.find(d=>d.id==='mini'),uplink=p.links.find(l=>(l.a===mini.id&&l.portA===(mini.uplinkPort||'P1'))||(l.b===mini.id&&l.portB===(mini.uplinkPort||'P1')));assert.ok(uplink);const socket=p.devices.find(d=>d.id===(uplink.a===mini.id?uplink.b:uplink.a)),front=uplink.a===socket.id?uplink.portA:uplink.portB;p.links=p.links.filter(l=>!((l.a===socket.id&&l.portA==='R'+front.slice(1))||(l.b===socket.id&&l.portB==='R'+front.slice(1))));const task=roomTasks(p,mini.room).find(t=>t.text.startsWith(mini.name+':'));assert.ok(task);assert.equal(task.device,socket.id);assert.equal(task.port,'R'+front.slice(1));});
