import test from 'node:test';
import assert from 'node:assert/strict';
import {searchDevice,formSnapshot,beginForm,formDirty,mayDiscard} from '../public/ux-feedback.js';
import {makeExample} from '../public/examples.js';
import {validateCableChoice} from '../public/connection-guide.js';
test('global search combines owner, equipment and location with accent-insensitive tokens',()=>{const p={sites:[{id:'s',name:'Câmara'}],floors:[{id:'f',name:'Piso 2'}],rooms:[{id:'r',name:'Contabilidade'}]};const d={name:'PC 01',site:'s',floor:'f',room:'r',record:{owner:'Ana Romão'}};assert.ok(searchDevice(p,d,'romao pc camara'));assert.ok(searchDevice(p,d,'contabilidade piso 2'));assert.equal(searchDevice(p,d,'Ana arquivo'),false);});
test('form guard distinguishes unchanged, modified and restored fields including file selections',()=>{const field={name:'quantity',type:'number',value:'1'},file={id:'upload',type:'file',value:''},form={elements:[field,file]},dialog={open:true,dataset:{},querySelector:()=>form,addEventListener(){}};beginForm(dialog);assert.equal(formDirty(dialog),false);field.value='6';assert.equal(formDirty(dialog),true);globalThis.confirm=()=>false;assert.equal(mayDiscard(dialog),false);field.value='1';assert.equal(formDirty(dialog),false);file.value='floor.png';assert.equal(formDirty(dialog),true);dialog.open=false;assert.equal(mayDiscard(dialog),true);delete globalThis.confirm;});
test('form snapshot detects checkbox state, ignores action buttons',()=>{const form={elements:[{name:'active',type:'checkbox',checked:false},{name:'save',type:'submit',value:'Save'}]};const before=formSnapshot(form);form.elements[1].value='Saving';assert.equal(formSnapshot(form),before);form.elements[0].checked=true;assert.notEqual(formSnapshot(form),before);});
test('occupied port error identifies the field and the existing peer',()=>{const p=makeExample('connections'),l=p.links.find(l=>l.id==='MINI-PC');assert.throws(()=>validateCableChoice(p,l),err=>err.field==='portA'&&err.message.includes(p.devices.find(d=>d.id===l.b).name));});
