import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';import worker from '../dist/server/index.js';import {demo} from '../public/demo.js';
const db=new DatabaseSync(':memory:');db.exec(fs.readFileSync('drizzle/0000_swift_shen.sql','utf8'));db.exec(fs.readFileSync('drizzle/0001_acoustic_scarecrow.sql','utf8'));const DB = {
 prepare(sql) {
  return {bind(...args) {
   return {
    async all() {return {results:db.prepare(sql).all(...args)};},
    async first() { return db.prepare(sql).get(...args) || null; },
    async run() {const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};}
   };
  }};
 }
};
function req(method,body,owner='test-user'){return new Request('https://atlas.example/api/project',{method,headers:{...(owner?{'oai-authenticated-user-id':owner}:{}),'Content-Type':'application/json','Origin':'https://atlas.example'},...(body?{body:JSON.stringify(body)}:{})});}
test('project API requires identity',async()=>assert.equal((await worker.fetch(req('GET',null,''),{DB})).status,401));
test('save/load, stale revision rejection and owner isolation',async()=>{const save=await worker.fetch(req('PUT',{project:demo,revision:0}),{DB});assert.equal(save.status,200);assert.equal((await save.json()).revision,1);const get=await worker.fetch(req('GET'),{DB});assert.equal((await get.json()).project.devices.length,23);const clash=await worker.fetch(req('PUT',{project:demo,revision:0}),{DB});assert.equal(clash.status,409);const other=await worker.fetch(req('GET',null,'other-user'),{DB});assert.equal((await other.json()).project,null);const update=await worker.fetch(req('PUT',{project:{...demo,name:'Updated'},revision:1}),{DB});assert.equal((await update.json()).revision,2);});
test('rejects corrupt project and cross-origin writes',async()=>{assert.equal((await worker.fetch(req('PUT',{project:{version:1},revision:0}),{DB})).status,400);const r=req('PUT',{project:demo,revision:0});r.headers.set('Origin','https://outside.example');assert.equal((await worker.fetch(r,{DB})).status,403);});
test('serves all required application modules',async()=>{for(const path of ['/','/app.js','/model.js','/demo.js','/plan.js','/scene.js','/features.js','/network.js','/vendor/three.module.js','/vendor/OrbitControls.js']){const r=await worker.fetch(new Request('https://atlas.example'+path),{DB});assert.equal(r.status,200,path);}});
function featureReq(path,method='GET',body,owner='feature-user'){return new Request('https://atlas.example'+path,{method,headers:{'oai-authenticated-user-id':owner,Origin:'https://atlas.example'},...(body?{body:typeof body==='string'||body instanceof Uint8Array?body:JSON.stringify(body)}:{})});}
test('named versions are immutable owner-scoped snapshots',async()=>{const saved=await worker.fetch(featureReq('/api/versions','POST',{label:'Before changes',project:demo}),{DB});assert.equal(saved.status,201);const {id}=await saved.json();const list=await worker.fetch(featureReq('/api/versions'),{DB});assert.equal((await list.json()).versions.length,1);const get=await worker.fetch(featureReq('/api/versions/'+id),{DB});assert.equal((await get.json()).project.devices.length,23);assert.equal((await worker.fetch(featureReq('/api/versions/'+id,'GET',null,'other'),{DB})).status,404);await worker.fetch(featureReq('/api/versions/'+id,'DELETE',null,'other'),{DB});assert.equal((await worker.fetch(featureReq('/api/versions/'+id),{DB})).status,200);await worker.fetch(featureReq('/api/versions/'+id,'DELETE'),{DB});assert.equal((await worker.fetch(featureReq('/api/versions/'+id),{DB})).status,404);});
test('floorplan uploads validate media and isolate asset reads by owner',async()=>{const data=new Map(),ATLAS_ASSETS={async put(key,body,meta){data.set(key,{body,httpMetadata:meta.httpMetadata});},async get(key){return data.get(key)||null;}};const env={DB,ATLAS_ASSETS};const image=new Uint8Array([137,80,78,71,13,10,26,10,0]);const uploaded=await worker.fetch(featureReq('/api/assets','POST',image),env);assert.equal(uploaded.status,201);const {id}=await uploaded.json();const read=await worker.fetch(featureReq('/api/assets/'+id),env);assert.equal(read.status,200);assert.equal(read.headers.get('content-type'),'image/png');assert.deepEqual(new Uint8Array(await read.arrayBuffer()),image);assert.equal((await worker.fetch(featureReq('/api/assets/'+id,'GET',null,'other'),env)).status,404);assert.equal((await worker.fetch(featureReq('/api/assets','POST','<svg/>'),env)).status,400);});
test('equipment attachments accept PDF, isolate owners and force document download',async()=>{const files=new Map(),ATLAS_ASSETS={async put(k,body,meta){files.set(k,{body,...meta});},async get(k){return files.get(k)||null;}};const env={DB,ATLAS_ASSETS},upload=featureReq('/api/equipment-files','POST','%PDF-1.7\nexample');upload.headers.set('X-File-Name',encodeURIComponent('garantia.pdf'));const response=await worker.fetch(upload,env);assert.equal(response.status,201);const meta=await response.json();assert.equal(meta.type,'application/pdf');const read=await worker.fetch(featureReq('/api/equipment-files/'+meta.id),env);assert.equal(read.status,200);assert.match(read.headers.get('content-disposition'),/^attachment/);assert.equal((await worker.fetch(featureReq('/api/equipment-files/'+meta.id,'GET',null,'another-owner'),env)).status,404);assert.equal((await worker.fetch(featureReq('/api/equipment-files','POST','<script>bad</script>'),env)).status,400);const noOrigin=featureReq('/api/equipment-files','POST','%PDF-1.7');noOrigin.headers.delete('Origin');assert.equal((await worker.fetch(noOrigin,env)).status,403);});

test('complete journey: build rooms, add equipment, connect, move, rotate, save through API and reopen',async()=>{
 const {createBuilding}=await import('../public/building-setup.js'),{createRoomDevices}=await import('../public/room-actions.js'),{normalizeProject,validate,uid}=await import('../public/model.js'),{validateCableChoice}=await import('../public/connection-guide.js'),{rotateEquipment}=await import('../public/equipment-rotation.js'),{moveToRoom}=await import('../public/plan-groups.js');
 const p=normalizeProject({version:3,name:'Percurso completo',sites:[],floors:[],rooms:[],racks:[],devices:[],links:[],nets:[],templates:[]});const building=createBuilding(p,{name:'Edifício de teste',floors:[{name:'Rés do chão',rooms:'Receção\nInformática'}]}),a=createRoomDevices(p,{roomId:building.rooms[0].id,name:'PC Receção',type:'Computador'})[0],b=createRoomDevices(p,{roomId:building.rooms[0].id,name:'Tomada Receção',type:'Tomada de rede'})[0];
 const link={id:uid('link'),a,b,portA:'Ethernet1',portB:'F1',kind:'copper',speed:'1 Gbps',vlans:[],label:'Cabo de teste',category:'Cat 6',color:'#3563c7',length:null,routeNote:'',waypoints:[]};validateCableChoice(p,link);p.links.push(link);const dest=building.rooms[1];moveToRoom(p,a,{x:building.site.x+dest.x,z:building.site.z+dest.z,rotation:0},dest.id);rotateEquipment(p,a,75);normalizeProject(p);validate(p);
 const saved=await worker.fetch(req('PUT',{project:p,revision:0},'journey-owner'),{DB});assert.equal(saved.status,200);const reopened=await worker.fetch(req('GET',null,'journey-owner'),{DB});assert.equal(reopened.status,200);const restored=(await reopened.json()).project;assert.deepEqual(restored,p);assert.equal(restored.devices.find(d=>d.id===a).rotation,75);assert.equal(restored.devices.find(d=>d.id===a).room,dest.id);assert.equal(restored.links.length,1);
});
