// Export encryption is server-side only. No key is included in public assets.
const SEALED_SITE='appgprj_6ab3b74fd9788191b898fe08435d211b';
const SEALED_LIMIT=1500000,SEALED_FILE_LIMIT=2100000;
const sealedEncoder=new TextEncoder(),sealedDecoder=new TextDecoder('utf-8',{fatal:true});
const sealedB64=bytes=>{let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);};
function sealedBytes(value,length,max=SEALED_FILE_LIMIT){if(typeof value!=='string'||value.length>max||!value.length||value.length%4||!/^[A-Za-z0-9+/]*={0,2}$/.test(value))throw new Error('Invalid envelope');const bytes=Uint8Array.from(atob(value),c=>c.charCodeAt(0));if((length!==undefined&&bytes.length!==length)||sealedB64(bytes)!==value)throw new Error('Invalid envelope');return bytes;}
function sealedConfig(env){try{const c=JSON.parse(env.ATLAS_EXPORT_KEYRING||'');if(!/^[a-zA-Z0-9_-]{1,40}$/.test(c.active)||!c.keys||!Object.hasOwn(c.keys,c.active)||Object.keys(c.keys).length>20)throw new Error();for(const [id,key] of Object.entries(c.keys)){if(!/^[a-zA-Z0-9_-]{1,40}$/.test(id))throw new Error();sealedBytes(key,32,44);}return c;}catch{throw new Error('KEY_UNAVAILABLE');}}
function sealedHeader(e){return {format:'ATLAS-SEALED',version:1,algorithm:'AES-256-GCM',kid:e.kid,salt:e.salt,iv:e.iv};}
async function sealedKey(master,owner,salt){const base=await crypto.subtle.importKey('raw',sealedBytes(master,32,44),'HKDF',false,['deriveKey']);return crypto.subtle.deriveKey({name:'HKDF',hash:'SHA-256',salt,info:sealedEncoder.encode(JSON.stringify(['atlas-export',1,SEALED_SITE,owner]))},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function sealProject(project,owner,config){validate(project);const plain=sealedEncoder.encode(JSON.stringify(project));if(plain.length>SEALED_LIMIT)throw new Error('SIZE_LIMIT');const salt=crypto.getRandomValues(new Uint8Array(32)),iv=crypto.getRandomValues(new Uint8Array(12));const header=sealedHeader({kid:config.active,salt:sealedB64(salt),iv:sealedB64(iv)}),key=await sealedKey(config.keys[config.active],owner,salt);const data=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:sealedEncoder.encode(JSON.stringify(header)),tagLength:128},key,plain);return {...header,data:sealedB64(new Uint8Array(data))};}
async function unsealProject(envelope,owner,config){if(!envelope||Array.isArray(envelope)||Object.keys(envelope).sort().join(',')!=='algorithm,data,format,iv,kid,salt,version'||envelope.format!=='ATLAS-SEALED'||envelope.version!==1||envelope.algorithm!=='AES-256-GCM'||typeof envelope.kid!=='string'||!Object.hasOwn(config.keys,envelope.kid))throw new Error('Invalid envelope');const salt=sealedBytes(envelope.salt,32,44),iv=sealedBytes(envelope.iv,12,16),data=sealedBytes(envelope.data);if(data.length<16||data.length>SEALED_LIMIT+16)throw new Error('Invalid envelope');const key=await sealedKey(config.keys[envelope.kid],owner,salt),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:sealedEncoder.encode(JSON.stringify(sealedHeader(envelope))),tagLength:128},key,data);return normalizeProject(validate(JSON.parse(sealedDecoder.decode(plain))));}
async function secureExportAPI(request,env,url,owner){if(!['/api/secure-export','/api/secure-import'].includes(url.pathname))return null;
 if(!owner)return json({error:'Inicie sessão na conta que exportou o ficheiro.'},401);
 if(request.method!=='POST')return json({error:'Método não permitido.'},405);
 // Browser-only API: reject missing Origin as well as foreign origins.
 if(request.headers.get('Origin')!==url.origin||request.headers.get('Sec-Fetch-Site')==='cross-site')return json({error:'Origem não autorizada.'},403);
 if(request.headers.get('Content-Type')?.split(';')[0].trim()!=='application/json')return json({error:'Formato de pedido não suportado.'},415);
 let config;try{config=sealedConfig(env);}catch{return json({error:'A proteção de exportações está indisponível. Não foi criado nenhum ficheiro sem encriptação.'},503);}
 const exporting=url.pathname==='/api/secure-export';let raw;
 try{raw=await readBounded(request,exporting?SEALED_LIMIT+100:SEALED_FILE_LIMIT);}catch{return json({error:'O ficheiro excede o tamanho permitido.'},413);}
 try{const input=JSON.parse(sealedDecoder.decode(raw));if(exporting){const envelope=await sealProject(input.project,owner,config);return new Response(JSON.stringify(envelope),{headers:{'Content-Type':'application/vnd.atlas.sealed+json','Content-Disposition':'attachment; filename="atlas-projeto.atlasenc"','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}const project=await unsealProject(input,owner,config);return json({project});
 }catch(err){if(exporting)return json({error:err.message==='SIZE_LIMIT'?'O projeto excede o limite de 1,5 MB.':'Não foi possível cifrar este projeto. Confirme que os dados são válidos.'},400);return json({error:'Não foi possível abrir o ficheiro. Pode pertencer a outra conta, estar alterado ou precisar de uma chave anterior.'},400);}
}
